spring.application.name=segment-service
spring.threads.virtual.enabled=true
server.port=9002

# gRPC server port
spring.grpc.server.port=9091

# Actuator endpoints
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true
