spring.application.name=ad-orchestration
spring.threads.virtual.enabled=true
server.port=8080

# gRPC client configuration
grpc.client.user-service.host=localhost
grpc.client.user-service.port=9090
grpc.client.segment-service.host=localhost
grpc.client.segment-service.port=9091
grpc.client.targeting-service.host=localhost
grpc.client.targeting-service.port=9092

# HTTP Client Configuration
http.client.connect-timeout=50ms
http.client.read-timeout=85ms
http.client.groups.mlinference=http://localhost:8081
http.client.groups.nike=http://localhost:8082/partners/nike
http.client.groups.adidas=http://localhost:8082/partners/adidas
http.client.groups.northface=http://localhost:8082/partners/northface

# 2. Native Resilience
resilience.retry.partners.max-retries=0
resilience.retry.partners.delay=0ms
resilience.retry.ml-inference.max-retries=0
resilience.retry.ml-inference.delay=0ms

# 3. Actuator & Metrics
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.metrics.distribution.percentiles-histogram.http.server.requests=true
