spring.application.name=ad-orchestration
spring.threads.virtual.enabled=true
server.port=8080

# gRPC client channels
spring.grpc.client.default-channel.negotiation-type=PLAINTEXT
spring.grpc.client.channels.user-service.address=localhost:9090
spring.grpc.client.channels.segment-service.address=localhost:9091
spring.grpc.client.channels.targeting-service.address=localhost:9092

# HTTP Client Configuration
http.client.connect-timeout=50ms
http.client.read-timeout=85ms
http.client.groups.mlinference=http://localhost:8081
http.client.groups.nike=http://localhost:8082/partners/nike
http.client.groups.adidas=http://localhost:8082/partners/adidas
http.client.groups.northface=http://localhost:8082/partners/northface

# 2. Native Resilience
resilience.retry.partners.max-retries=0
resilience.retry.partners.delay=0ms
resilience.retry.ml-inference.max-retries=0
resilience.retry.ml-inference.delay=0ms

# 3. Actuator & Metrics
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.metrics.distribution.percentiles-histogram.http.server.requests=true
